sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hdfRimRukAVtsn0I/CAOo0nc38CtN0JYmF8p1PAT0InQST6QJ9Q7K08OXuqryckbR8S90HNBqS//MyxMl0BB5DY1lLe+Bs9PrcpoKCDy5rphMo7MxmB8TriQ6K33SWGJSx26KT+jowB1j4kBneIVz81P8LXZWx27Lq8exyKYxKeMnv49pNHlYWw101expSvqEtRc3ARhJiOk3aRKQy0kvpFEOd/M7bho+qjDNLZuO7SIBxCXBdlpOhFdlKnEM1H8Wzbqa0BeWYTrD5J668Hhj+mHy+ct2bcGbLu7UawD9wny/rHfYagLCrHXMQXA7ML3wRB+SfETQ1+h6R59uNNpBywgjPlwPfjlxAuOqwIRUx9EwGgshhwbsjjK7Mn7syzlzxkywbSzwhVT9qvslVLV3gkYuDsbdD6zGmVC+Nk8s8/rpuzDamA9PGxas2AtrQEpdNWCXsMVU28ELrlY39wz/M2LEH8FoADktoSNi22udOFC7HEf0dGH3AgsytzoQosKSaHHeE4bu3QgCbXCJCAqvKOXUMKJ4kj/hdPMrEiccV4cd8Wmi6Y72RZmJnB9Chkg9U7GKHe4c3oarIRIYmVYri4+Dndq3B+yK3we7jOd8yn8FZk/8aAgzxQZQ1euZilngDrfj25lW4AK5Xh6hK8mTNWDunkTChdBWnfjCM+/Gt4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Lover-s-Vows_4554
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy